service: web-anuncios
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  stage: dev
  environment:
    AD_TABLE: AdTable
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.AD_TABLE}"

functions:
  create:
    handler: handler.createAd
    events:
      - http: 
          method: POST
          path: /
          cors: true
  getAllAds:
    handler: handler.getAllAds
    events:
      - http: 
          method: GET
          path: /advertisements
          cors: true
  getAdvertisement:
    handler: handler.getAdvertisement
    events:
      - http:
          method: GET
          path: /advertisements/{adv}
          cors: true
          request:
            parameters:
              paths:
                adv: true
  addComments:
    handler: handler.addComments
    events:
      - http:
          method: POST
          path: /advertisements/{adv}
          cors: true
          request:
            parameters:
              paths:
                adv: true
resources:
  Resources:
    AdTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: adId
            AttributeType: S
        KeySchema:
          - AttributeName: adId
            KeyType: HASH
        TableName: ${self:provider.environment.AD_TABLE}
        BillingMode: PAY_PER_REQUEST
    AdvertisementsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: advertisements-olga-penedo
        WebsiteConfiguration:
          IndexDocument: index.html
    AdvertisementsBucketPolicy: 
      Type: AWS::S3::BucketPolicy
      Properties: 
        Bucket:
          Ref: "AdvertisementsBucket"
        PolicyDocument:
          Statement:
            -
              Effect: "Allow"
              Principal: "*"
              Action:
                - "s3:GetObject"
              Resource:
                Fn::Join:
                  - ""
                  - 
                    - "arn:aws:s3:::"
                    - 
                      Ref: "AdvertisementsBucket"
                    - "/*"
  Outputs:
    AdvertisementsBucketURL:
      Description: "Advertisements website URL"
      Value: 
        "Fn::GetAtt": [ AdvertisementsBucket, WebsiteURL ]


